name: Ulayzer
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.0.0
  permission_handler: ^12.0.0
  flutter_sms_inbox: ^1.0.3
  url_launcher: ^6.3.0
  http: ^1.3.0
  flutter_background_service_android: ^6.3.0
  device_info_plus: ^11.0.0
  android_intent_plus: ^5.3.0
  sqflite: ^2.4.0
  path_provider: ^2.1.4
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  uuid: ^4.4.0
  fl_chart: ^0.70.0
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logom.png
    - assets/ulogi.png
    - assets/google_icon.png
    - assets/virustotal_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/ulogi.png"
  min_sdk_android: 23